unit TestParser;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework
  , uParser
  , SysUtils
  ;

type
  // Test methods for class TParser

  TestTParser = class(TTestCase)
  published
    procedure TestSomeDo;
    procedure FirstTest;
  end;

implementation

procedure TestTParser.FirstTest;
begin
  Check(True);
end;

procedure TestTParser.TestSomeDo;
var
  l_In: string;
  l_Parser : TscriptParser;
begin
  l_Parser := TscriptParser.Create;

  FreeAndNil(l_Parser);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTParser.Suite);
end.

