unit TestmsJsonFormatter;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework,
  Data.DBXJSONReflect,
  JSON,
  FMX.Objects,
  msFormatter
  ;

type
  // Test methods for class TmsSerializeController

  TestTmsSerializeController = class(TTestCase)
  published
    procedure TestFormat;
  end;

implementation

 uses
  System.SysUtils,
  System.Types,
  System.Classes,
  msStringList
  ;

 const
  c_JsonBeforeFormat = 'JsonBeforeFormat.json';
  c_FileNameEtalon = 'JsonFormatEtalon.json';

procedure TestTmsSerializeController.TestFormat;
var
  l_JsonFileBeforeFormat,
  l_FileEtalon, l_Result: TmsStringList;
begin
 l_JsonFileBeforeFormat := TmsStringList.Create;
 try
  l_JsonFileBeforeFormat.LoadFromFile(c_JsonBeforeFormat);
  l_FileEtalon := TmsStringList.Create;
  try
   l_FileEtalon.LoadFromFile(c_FileNameEtalon);
   l_Result := TmsStringList.Create;
   try
    // TODO: Setup method call parameters
    l_Result.Text:= TmsFormatter.FormatJson(l_JsonFileBeforeFormat.Text);
    l_Result.SaveToFile(ExtractFilePath(ParamStr(0)) +  '\json.json');
    // TODO: Validate method results
    CheckTrue(l_FileEtalon.Equals(l_Result));
   finally
    FreeAndNil(l_Result);
   end;//try..finally
  finally
   FreeAndNil(l_FileEtalon);
  end;//try..finally
 finally
  FreeAndNil(l_JsonFileBeforeFormat);
 end;//try..finally
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTmsSerializeController.Suite);
end.


