unit TestMsCircle;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, FMX.Types, msShape, msCircle, System.UITypes, FMX.Graphics,
  System.Types,
  msInterfaces
  ;

type
  // Test methods for class TmsCircle

  TestTmsCircle = class(TTestCase)
  strict private
    FmsCircle: ImsShape;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestContainsPt;
  end;

implementation

uses
 msShapeCreator
 ;

procedure TestTmsCircle.SetUp;
begin
  FmsCircle := TmsCircle.MC.CreateShape(TPointF.Create(0, 0));
end;

procedure TestTmsCircle.TearDown;
begin
  FmsCircle := nil;
end;

procedure TestTmsCircle.TestContainsPt;
var
 l_HitShape: ImsShape;
begin
 CheckTrue(FmsCircle.HitTest(TPointF.Create(0, 0), l_HitShape));
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTmsCircle.Suite);
end.

