// Разработчик: Селянкин Владимир

: K378550793

 : Действия
  OBJECT VAR "Тулбар"
 'tbcfAttributeSelectBottom' "Найти окно атрибутов" pop:control:FindControlByName =: "Тулбар"
 "Тулбар" pop:object:IsNil ! 'Не удалось найти тулбар' ASSERTS 
 "Тулбар" pop:control:GetHeight РАВНО 0 .
 ;

 ППР
 "Убедиться, что фокус в редакторе"
 'AT_TYPE' focused:control:push pop:QueryCard:Attribute:SetFocus
 "Обработать Enter модально" ( Действия )
;

K378550793