//тесты для проверки правильности фильтрации поля Номер в ППР (эталоны для базы preview_10_08_13): [$482754771]

PROCEDURE K483398400

 INTEGER VAR aContext
 STRING VAR aContext_str
 0 >>> aContext
 10 раз ( 
  aContext IntToStr >>> aContext_str
  "Ввести контекст {(aContext_str)} в контекстный фильтр модального окна 'Номер' и, если он корректен и кол-во номеров меньше 100 000, сравнить их с эталоном"
  ++! aContext
 ) 
;

K483398400
