PROGRAM CacheFunction.ms.script

USES
 Testing.ms.dict
;

Test&Dump CacheFunction.ms.script.test

 : Cache
 ; // Cache

 : A

  STRING FUNCTION X
   '1' >>> Result
  ; // X

  ERROR 'fake A'
 ; // A

 : B

  STRING FUNCTION X
   '2' >>> Result
  ; // X

  ERROR 'fake B'
 ; // B

 STRING FUNCTION X
   TtfwWord IN aWord
  Cache ( aWord %% 'X' pop:Word:Name ) >>> Result
 ; // X

 @ A X .
 @ B X .
; // CacheFunction.ms.script.test

CacheFunction.ms.script.test
