PROGRAM CallInherited.ms.script

USES
 WordsRTTI.ms.dict
 Testing.ms.dict
;

Test&Dump CallInheritedTest

MACRO call.inherited
 // - пон€тно, что это надо делать через честную компил€цию ссылки на Inherited
 [ 
   '@SELF .Inherited.Words .for> ( Self SWAP DO )'
 ] Ctx:Parser:PushArray
; // call.inherited

 : A
  INTEGER IN Self
  Self 1 +
 ; // A

 : B
  INTEGER IN Self
  Self 2 +
  call.inherited
 ; // B

 1 A .
 1 B .

; // CallInheritedTest

CallInheritedTest
