PROGRAM CallParentInherited.ms.script

USES
 classRelations.ms.dict
;

USES
 Testing.ms.dict
;

Test&Dump CallParentInheritedTest

 MACRO call.ancestor
 ; // call.ancestor

 : A
  : X
    INTEGER IN aValue
   aValue 1 +
  ; // X
 ; // A

 : B Inherits A
  : X
    INTEGER IN aValue
   aValue 2 + A :: X
  ; // X
 ; // B

 1 A :: X .
 2 B :: X .

; // CallParentInheritedTest

CallParentInheritedTest
