: LW
  STRING IN aWordName
  STRING IN aDictName
 STRING VAR l_FileName
 sysutils:GetCurrentDir >>> l_FileName 
 [ l_FileName '\' aWordName '.' aDictName ] strings:Cat >>> l_FileName
 l_FileName .

 FILE VAR l_File

 l_FileName File:OpenWrite >>> l_File
 TRY
 FINALLY
  nil >>> l_File
 END
; // LW

'X' 'CompileAndProcess.used.ms.dict' LW

VAR l_Ptr
'CompileAndProcess.ms.dict' script:CompileAndProcess DO
>>> l_Ptr
l_Ptr DO .