PROGRAM DelegateToGen.ms.script

USES
 Testing.ms.dict
;

Test&Dump DelegateToGen

 TtfwWord VAR g_Gen

 MACRO .?
   ^ IN aWord

  STRING VAR l_Name
  aWord pop:Word:Name >>> l_Name
  l_Name .

  Ctx:PushFinder CompileWeakRef
  @ DO CompileRef
  @ . CompileValue

  //aWord DO
 ; // .?

 : Gen
  : A
  ; // A
 ; // Gen

 : A
  1
 ; // A

 @ Gen >>> g_Gen

 .? A . 
 A .
; // DelegateToGen

DelegateToGen
