PROGRAM DelegateToGen.ms.script

USES
 Testing.ms.dict
;

Test&Dump DelegateToGen

 TtfwWord VAR g_Gen

 MACRO .?
   ^ IN aWord

  STRING VAR l_Name
  aWord pop:Word:Name >>> l_Name
  l_Name .

  axiom:PushStringAsSymbol l_Name

 ; // .?

 : Gen
  : A
  ; // A
 ; // Gen

 : A
  1 +
 ; // A

 : B
  2 +
 ; // B

 : C
  3 +
 ; // C

 : D
  4 +
 ; // D

 @ Gen >>> g_Gen

 1 .? A . 
 1 .? B . 
 1 .? C . 
 1 .? D . 
 1 A .
; // DelegateToGen

DelegateToGen
