USES
 macro.ms.dict
 arrays.ms.dict
 io.ms.dict
 Testing.ms.dict
;


Test&Dump ITTest

operator IT 
  ARRAY IN A
  ^ IN aWhatToDo
 %SUMMARY 'Итерирует массив A вызывая лямбду aWhatToDo' ;
 aWhatToDo A ITERATE
; // IT

operator for
  ^ IN aList
  ^ IN aWhatToDo
 %SUMMARY 'Итерирует массив aList вызывая лямбду aWhatToDo' ;
 aList DO ==> ( aWhatToDo DO )
; // for

 [ 1 2 3 4 5 6 7 8 9 10 ] IT Print

 for [ 1 2 3 4 5 6 7 8 9 10 ] Print

; // ITTest

ITTest