USES
 io.ms.dict
 Object.ms.dict
 Testing.ms.dict
;

USES
 axiom:WordInfo
;

Test&Dump ObjectTest

 @ _:Object DumpElement

 //_:Object .

 Object VAR l_Obj
 l_Obj := Object:new

 l_Obj .Print
 l_Obj .ClassName Print

 @ l_Obj pop:Word:Info pop:WordInfo:ValueTypes Print
 @ l_Obj pop:Word:Info pop:WordInfo:ValueTypes pop:ValueTypes:Name Print
 l_Obj .ClassName Print
 l_Obj .InstanceSize Print

 _:Object pop:Word:Name Print
 _:Object pop:Word:Name Print

; // ObjectTest

ObjectTest