USES
 io.ms.dict
 Object.ms.dict
 Testing.ms.dict
;

USES
 axiom:WordInfo
;

Test&Dump ObjectTest

STRING operator |>
 IN anObject
 anObject pop:Word:Info pop:WordInfo:ValueTypes pop:ValueTypes:Name >>> Result
; // |>

 Object VAR l_Obj
 l_Obj := Object:new

 l_Obj Object:Print

 @ l_Obj pop:Word:Info pop:WordInfo:ValueTypes Print
 @ l_Obj pop:Word:Info pop:WordInfo:ValueTypes pop:ValueTypes:Name Print
 @ l_Obj |> Print

; // ObjectTest

ObjectTest