// SaveVarAndDo.ms.script

USES
 core.ms.dict
 params.ms.dict
 macro.ms.dict
 io.ms.dict
 Documentation.ms.dict
 Testing.ms.dict
;

Test&Dump SaveVarAndDoTest

PROCEDURE Trace
 IN aValue
 aValue Print
; // Trace

PROCEDURE SaveVarAndDo
 RIGHT IN aVar
 aVar |N Trace

 VAR l_OldValue
 l_OldValue := ( aVar |^ )
 l_OldValue Trace
 TRY
 FINALLY
 END
; // SaveVarAndDo

VAR A
A := '1'
A Print

SaveVarAndDo A

A Print

; // SaveVarAndDoTest

SaveVarAndDoTest