USES
 string.ms.dict
 Testing.ms.dict
;

RunTests (+)?
'------------------' Print

RunTests ?(+)
'------------------' Print

strings:CatSep> ' ' [ 'A' 'B' ] Print
strings:CatSep> ' ' [ 'A ' 'B' ] Print
strings:CatSep> ' ' [ 'A ' ' B' ] Print
strings:CatSep> ' ' [ 'A' ' B' ] Print
strings:CatSep> ' ' [ '' 'B' ] Print
strings:CatSep> ' ' [ 'A' '' ] Print
'------------------' Print

RunTests any:Cat
'------------------' Print