USES
 string.ms.dict
 Testing.ms.dict
;

PROCEDURE string:Split:for>
  STRING IN aString
  STRING IN aSep
  ^ IN aLambda
 aSep string:SplitTo! aString
 aLambda DO
 aString aLambda DO
; // string:Split:for>

Test&Dump StringTest
 RunTests.in.array @[ (+)? ?(+) strings:CatSep> any:Cat ]
  %REMARK 'Запускаем тесты к указанным скриптовым словам'

 'a b c' ' ' string:Split:for> .
; // StringTest

StringTest