// Testing.ms.script

USES
 implementation.ms.dict
 Testing.ms.dict
;

Test TestingTest

STRING FUNCTION (+)?
 STRING in aPrefix
 STRING right aSuffix
 %SUMMARY 'Если aSuffix не пустой, то возвращает сумму aPrefix и aSuffix, иначе возвращает пустую строку' ;
 Result := ''
 STRING VAR l_Suffix
 aSuffix =: l_Suffix
 if ( l_Suffix =/= '' ) then
  ( aPrefix l_Suffix Cat =: Result )
; // (+)?

MACRO Tests
 [
 ] Ctx:Parser:PushArray
; // Tests

implementation (+)?
 %%Tests
  Test T1 '' (+)? 'B' Print ;
  Test T2 'A' (+)? 'B' Print ;
  Test T3 'A' (+)? '' Print ;
 ; // %%Tests
end.

USES
 CodeDump.ms.dict
;

@SELF DumpElement

; // TestingTest

TestingTest