: TestExit
 'Сюда попали' .
 EXIT
 'Сюда никогда не попадём' .
;

: TestExit1
 'Сюда попали' .
 ( EXIT )
 'Сюда никогда не попадём' .
;

: TestExit2
 'Сюда попали' .
 Если ДА то ( EXIT )
 'Сюда никогда не попадём' .
;

: TestExit3
 'Сюда попали' .
 Если ДА ( EXIT )
 'Сюда никогда не попадём' .
;

: TestExit4
 'Сюда попали' .
 Если НЕТ то
  ( NOP )
 иначе
  ( EXIT ) 
 'Сюда никогда не попадём' .
;


TestExit
TestExit1
TestExit2
TestExit3
TestExit4
