USES
 Translate.ms.dict
;

перебрать ( ( 1 to 20 ) >filter> IsOdd >map> Inc1 >reverted> ) Print
// - печатаем нечётные числа + 1
'-------------------' Print
перебрать ( ( 1 to 20 ) >filter> IsEven >map> Inc1 >reverted> ) Print
// - печатаем чётные числа + 1

перебрать ( ( 1 to 20 ) >filter> IsOdd >map> Dec1 >reverted> ) Print
// - печатаем нечётные числа - 1
'-------------------' Print
перебрать ( ( 1 to 20 ) >filter> IsEven >map> Dec1 >reverted> ) Print
// - печатаем чётные числа - 1
