PROCEDURE PrintThis
 ^ IN aValue
 aValue DO Print
; // PrintThis

: Process
 STRING IN aDir

 FORWARD ProcessItem

 : DoDir
  STRING IN aDir

  : DoFile
   STRING IN anFilePath
   PrintThis anFilePath
  ; // DoFile

  for [ '*.ms.script' '*.ms.dict' '*.pas' '*.txt' '*.inc' '*.fmx' '*.xml' '*.dpr' ] (
   STRING IN aMask
   IterateFilesWithMask aDir aMask DoFile
  )
 ; // DoDir

 : ProcessItem
  STRING IN aDir
  aDir DoDir
  IterateDirs aDir ProcessItem
 ; // ProcessItem

 aDir ProcessItem
; // Process

'..\..\' Process