VOID IMMEDIATE operator RecurseProc
// - процедура, которая умеет вызываться рекурсивно
 ^L IN aName
 'FORWARD' Ctx:Parser:PushSymbol
 aName |N Ctx:Parser:PushSymbol

 ':' Ctx:Parser:PushSymbol
 aName |N Ctx:Parser:PushSymbol
; // RecurseProc

PROCEDURE ProcessDirs
 RightParam aDir

 PROCEDURE DoDir
  RightParam aDir

  PROCEDURE DoFile
   STRING IN anFilePath
   PrintThis anFilePath
  ; // DoFile

  for [ '*.ms.script' '*.ms.dict' '*.pas' '*.txt' '*.inc' '*.fmx' '*.xml' '*.dpr' ] (
   STRING IN aMask
   IterateFilesWithMask aDir aMask DoFile
  )
 ; // DoDir

 RecurseProc ProcessItem
  STRING IN aDir
  DoDir aDir
  IterateDirs aDir ProcessItem
 ; // RecurseProc

 aDir DO ProcessItem
; // ProcessDirs

ProcessDirs '..\..\'