PROCEDURE ProcessSubDirsWithMasks
 RightParam aRoot
 RightParam aMaskArray
 RightParam aLambda

 PROCEDURE DoDir
  RightParam aDir

  PROCEDURE DoFile
   STRING IN anFilePath
   anFilePath aLambda |@ DO
  ; // DoFile

  for ( aMaskArray |^ ) (
   STRING IN aMask
   IterateFilesWithMask aDir aMask DoFile
  )
 ; // DoDir

 PROCEDURE ProcessItem
  STRING IN aDir
  DoDir aDir
  IterateDirs aDir ( this.do )
 ; // ProcessItem

 aRoot DO ProcessItem
; // ProcessSubDirsWithMasks

ProcessSubDirsWithMasks '..\..\' [ '*.ms.script' '*.ms.dict' '*.pas' '*.txt' '*.inc' '*.fmx' '*.xml' '*.dpr' ] Print