FORWARD Process

: Process
 STRING IN aDir

 FORWARD ProcessItem

 : DoDir
  STRING IN anItem

  : DoFile
   STRING IN anItem
   anItem .
  ; // DoFile

  @ DoFile '*.ms.script' anItem ProcessFilesWithMask
  @ DoFile '*.ms.dict' anItem ProcessFilesWithMask
  @ DoFile '*.pas' anItem ProcessFilesWithMask
  @ DoFile '*.txt' anItem ProcessFilesWithMask
  @ DoFile '*.inc' anItem ProcessFilesWithMask
  @ DoFile '*.fmx' anItem ProcessFilesWithMask
  @ DoFile '*.xml' anItem ProcessFilesWithMask
  @ DoFile '*.dpr' anItem ProcessFilesWithMask
 ; // DoDir

 : ProcessItem
  STRING IN anItem
  anItem DoDir
  @ ProcessItem anItem ProcessSubDirs
 ; // ProcessItem

 aDir ProcessItem
; // Process

'..\..\' Process