PROCEDURE ProcessDirs

 RightParam aDir

VOID IMMEDIATE OPERATOR this.do
 Ctx:KeyWordDefiningNow CompileValue @ DO CompileValue
; // this.do

 PROCEDURE DoDir
  RightParam aDir

  PROCEDURE DoFile
   STRING IN anFilePath
   PrintThis anFilePath
  ; // DoFile

  for [ '*.ms.script' '*.ms.dict' '*.pas' '*.txt' '*.inc' '*.fmx' '*.xml' '*.dpr' ] (
   STRING IN aMask
   IterateFilesWithMask aDir aMask DoFile
  )
 ; // DoDir

 RecurseProc ProcessItem
  STRING IN aDir
  DoDir aDir
  IterateDirs aDir ProcessItem
 ; // RecurseProc

 aDir DO ProcessItem
 @SELF DumpElement
; // ProcessDirs

ProcessDirs '..\..\'