PROCEDURE ProcessDirs
 STRING IN aDir

 FORWARD ProcessItem

 PROCEDURE DoDir
  ^ IN aDir

  PROCEDURE DoFile
   STRING IN anFilePath
   PrintThis anFilePath
  ; // DoFile

  for [ '*.ms.script' '*.ms.dict' '*.pas' '*.txt' '*.inc' '*.fmx' '*.xml' '*.dpr' ] (
   STRING IN aMask
   IterateFilesWithMask ( aDir DO ) aMask DoFile
  )
 ; // DoDir

 PROCEDURE ProcessItem
  STRING IN aDir
  DoDir aDir
  IterateDirs aDir ProcessItem
 ; // ProcessItem

 aDir ProcessItem
; // ProcessDirs

'..\..\' ProcessDirs