 @ [ 1 2 3 [ 4 5 [ 6 7 8 ] 9 ] 10 ] DumpElement
 @ ( 1 2 3 ( 4 5 [ 6 7 8 ] 9 ) 10 ) DumpElement
 @ ( 1 2 3 ( 4 5 ( 6 7 8 ) 9 ) 10 ) DumpElement
 @ ( VAR X ) DumpElement
 @ ( INTEGER VAR X ) DumpElement
 @ ( STRING VAR X ) DumpElement
 @ ( BOOLEAN VAR X ) DumpElement
 @ ( ATOMIC VAR X ) DumpElement
 @ ( ORDINAL VAR X ) DumpElement
 @ ( COMPARABLE VAR X ) DumpElement
 @ ( OBJECT VAR X ) DumpElement
 @ ( INTERFACE VAR X ) DumpElement