
FORWARD Process

: Process
 STRING IN aDir

 FORWARD ProcessItem

 : DoDir
  STRING IN anItem

  : DoFile
   STRING IN anItem
   anItem Print
  ; // DoFile

  for [ '*.ms.script' '*.ms.dict' '*.pas' '*.txt' '*.inc' '*.fmx' '*.xml' '*.dpr' ] (
   STRING IN aMask
   IterateFilesWithMask anItem aMask DoFile
  )
 ; // DoDir

 : ProcessItem
  STRING IN anItem
  anItem DoDir
  IterateDirs anItem ProcessItem
 ; // ProcessItem

 aDir ProcessItem
; // Process

'..\..\' Process