VOID IMMEDIATE operator RightParam
 'RIGHT' Ctx:Parser:PushSymbol
 'IN' Ctx:Parser:PushSymbol
; // RightParam

PROCEDURE ProcessDirs
 RightParam aDir

 FORWARD ProcessItem

 PROCEDURE DoDir
  RightParam aDir

  PROCEDURE DoFile
   STRING IN anFilePath
   PrintThis anFilePath
  ; // DoFile

  for [ '*.ms.script' '*.ms.dict' '*.pas' '*.txt' '*.inc' '*.fmx' '*.xml' '*.dpr' ] (
   STRING IN aMask
   IterateFilesWithMask aDir aMask DoFile
  )
 ; // DoDir

 PROCEDURE ProcessItem
  STRING IN aDir
  DoDir aDir
  IterateDirs aDir ProcessItem
 ; // ProcessItem

 aDir DO ProcessItem
; // ProcessDirs

ProcessDirs '..\..\'