FORWARD Process

PROCEDURE IterateFilesWithMask
  ^ IN aDir
  ^ IN aMask
  ^ IN aLambda
  aLambda aMask DO aDir DO ProcessFilesWithMask
; // IterateFilesWithMask

: Process
 STRING IN aDir

 FORWARD ProcessItem

 : DoDir
  STRING IN anItem

  : DoFile
   STRING IN anItem
   anItem .
  ; // DoFile

  for [ '*.ms.script' '*.ms.dict' '*.pas' '*.txt' '*.inc' '*.fmx' '*.xml' '*.dpr' ] (
   STRING IN aMask
   IterateFilesWithMask anItem aMask DoFile
  )
 ; // DoDir

 : ProcessItem
  STRING IN anItem
  anItem DoDir
  @ ProcessItem anItem ProcessSubDirs
 ; // ProcessItem

 aDir ProcessItem
; // Process

'..\..\' Process