USES
 CodeDump.ms.dict
;

Test TestCompileValue

 STRING VAR S
 [EXECUTE] ( S := 'Hello' )

 S := 'World'
 
 INTEGER VAR I
 [EXECUTE] ( I := 20 )
 
 I := 30
 
 [EXECUTE] ( I CompileValue ) .
 [EXECUTE] ( S CompileValue ) .

 OBJECT VAR O
 [EXECUTE] ( O := @ . )
 
 [EXECUTE] ( S CompileValue O CompileValue )

 [EXECUTE] ( 'ãû ãû ãû' CompileValue @ . CompileValue )
 
 'ãû ãû ãû 2' [EXECUTE] ( @ . CompileValue )
 
 I .
 S .
 
 @SELF DumpElement
 
; // TestCompileValue

TestCompileValue